version: '3.3'
services:
# Eureka Server      
  eurekasvc:
    build: eureka-service
    container_name: eurekasvc
    image: bookingaap/eurekasvc:1.0.0
    ports:
    - "8761:8761" 
    networks:
      - microservicesnet
    environment:
      EUREKA_HOST_NAME: 34.232.50.167
# Doctor service
  bookingsvc:
    build: doctor-service
    container_name: doctorsvc
    image: bookingaap/doctorsvc:1.0.0
    ports:
    - "8081:8081"
    networks:
      - microservicesnet
    environment:
      DOCTOR_SERVICE_PORT: 8081
      MONGO_HOST: sweethome.ce1r6snav3ls.us-east-1.rds.amazonaws.com
      MONGO_PORT: 27017
      MONGO_DATABASE: upgrad
      SQL_DATABASE: sweethome
      SQL_USER: admin
      SQL_PASSWORD: rootroot
      SQL_ROOT_PASSWORD: rootroot
      EUREKA_HOST_NAME: 34.232.50.167
      KAFKA_HOST: ec2-3-220-49-19.compute-1.amazonaws.com
      S3_ACCESS_KEY: AKIAQZIJ7MWRTEJGYUMV
      S3_SECRET_KEY: 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
    depends_on:
      - eurekasvc 
# User service
  usersvc:
    build: booking-service
    container_name: bookingsvc
    image: bookingaap/bookingsvc:1.0.0
    ports:
    - "8082:8082"
    networks:
      - microservicesnet
    environment:
      USER_SERVICE_PORT: 8082
      MONGO_HOST: sweethome.ce1r6snav3ls.us-east-1.rds.amazonaws.com
      MONGO_PORT: 27017
      MONGO_DATABASE: upgrad
      EUREKA_HOST_NAME: 34.232.50.167
      KAFKA_HOST: ec2-3-220-49-19.compute-1.amazonaws.com
      S3_ACCESS_KEY: AKIAQZIJ7MWRTEJGYUMV
      S3_SECRET_KEY: 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
    depends_on:
      - eurekasvc 
# Appointment service
  appointmentsvc:
    build: appointment-service
    container_name: appointmentsvc
    image: bookingaap/appointmentsvc:1.0.0
    ports:
    - "8083:8083"
    networks:
      - microservicesnet
    environment:
      APPOINTMENT_SERVICE_PORT: 8083
      SQL_HOST: sweethome.ce1r6snav3ls.us-east-1.rds.amazonaws.com
      SQL_DATABASE: upgrad
      SQL_USER: admin
      SQL_PASSWORD: rootroot
      SQL_ROOT_PASSWORD: rootroot
      MONGO_HOST: sweethome.ce1r6snav3ls.us-east-1.rds.amazonaws.com
      MONGO_PORT: 27017
      MONGO_DATABASE: upgrad
      EUREKA_HOST_NAME: 34.232.50.167
      KAFKA_HOST: ec2-3-220-49-19.compute-1.amazonaws.com
    depends_on:
      - eurekasvc 
# Payment service
  paymentsvc:
    build: payment-service
    container_name: bookingsvc
    image: bookingaap/paymentsvc:1.0.0
    ports:
    - "8084:8084"
    networks:
      - microservicesnet
    environment:
      PAYMENT_SERVICE_PORT: 8084
      SQL_HOST: sweethome.ce1r6snav3ls.us-east-1.rds.amazonaws.com
      SQL_DATABASE: sweethome
      SQL_USER: admin
      SQL_PASSWORD: rootroot
      SQL_ROOT_PASSWORD: rootroot
      EUREKA_HOST_NAME: 34.232.50.167
      KAFKA_HOST: ec2-3-220-49-19.compute-1.amazonaws.com
    depends_on:
      - eurekasvc
# Rating service
  ratingsvc:
    build: rating-service
    container_name: ratingsvc
    image: bookingaap/ratingsvc:1.0.0
    ports:
    - "8085:8085"
    networks:
      - microservicesnet
    environment:
      RATING_SERVICE_PORT: 8085
      SQL_HOST: sweethome.ce1r6snav3ls.us-east-1.rds.amazonaws.com
      SQL_DATABASE: sweethome
      SQL_USER: admin
      SQL_PASSWORD: rootroot
      SQL_ROOT_PASSWORD: rootroot
      EUREKA_HOST_NAME: 34.232.50.167
      KAFKA_HOST: ec2-3-220-49-19.compute-1.amazonaws.com
    depends_on:
      - eurekasvc 
# Notification service
  notificationsvc:
    build: notification-service
    container_name: notificationsvc
    image: bookingaap/notificationsvc:1.0.0
    ports:
    - "8086:8086"
    networks:
      - microservicesnet
    environment:
      NOTIFICATION_SERVICE_PORT: 8086
      EUREKA_HOST_NAME: 34.232.50.167
      KAFKA_HOST: ec2-3-220-49-19.compute-1.amazonaws.com:9092
      SES_ACCESS_KEY: AKIAQZIJ7MWR6TGENQMH
      SES_SECRET_KEY: BIui+1/WvKu/FaCbTRNNmn2DyDy9m/YsrbYgMuVXy4hM
      SES_FROM_EMAIL: anubhavh3@gmail.com
    depends_on:
      - eurekasvc     
# API Gateway
  notificationsvc:
    build: apigateway
    container_name: apigatewaysvc
    image: bookingaap/apigatewaysvc:1.0.0
    ports:
    - "8083:8083"
    networks:
      - microservicesnet
    environment:
      EUREKA_HOST_NAME: 34.232.50.167
    depends_on:
      - eurekasvc 
networks:
  microservicesnet:
    driver: bridge
